version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
  employee-api-container:
    image: employee-api
    container_name: employee-api-container
    ports:
      - 9002:9002
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone