server:
    port: 9002

spring:
  datasource:
    hikari:
      initialization-fail-timeout: 0

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    hikari:
#      initialization-fail-timeout: 0
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#      
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/employee_db?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: 
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true