apiVersion: v1
kind: Service
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  selector:
    app: employee-api
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
      - name: employee-api
        image: martinosearch/employee-api
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: employee_db
          - name: DB_USER
            value: martin
          - name: DB_PASSWORD
            value: "@Martin2020"
    

