apiVersion: v1
kind: Service
metadata:
  name: employee-api
spec:
  selector:
    app: employee-api
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
      - name: employee-api
        image: martinosearch/employee-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 9002
    

